export enum UserRole {
  PASSENGER = 'PASSENGER',
  OPERATOR_ADMIN = 'OPERATOR_ADMIN',
  OPERATOR_USER = 'OPERATOR_USER',
  CONDUCTOR = 'CONDUCTOR',
  DRIVER = 'DRIVER',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  PLATFORM_SUPERADMIN = 'PLATFORM_SUPERADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  DELETED = 'DELETED',
}

export enum PassengerType {
  ADULT = 'ADULT',
  CHILD = 'CHILD',
  STUDENT = 'STUDENT',
  SENIOR = 'SENIOR',
  CONCESSION = 'CONCESSION',
}

export enum OperatorStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED',
}

export enum OperatorUserRole {
  OPERATOR_ADMIN = 'OPERATOR_ADMIN',
  ROUTE_MANAGER = 'ROUTE_MANAGER',
  FARE_MANAGER = 'FARE_MANAGER',
  FLEET_MANAGER = 'FLEET_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
}

export enum StaffStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum BusCategory {
  ORDINARY = 'ORDINARY',
  SEMI_LUXURY = 'SEMI_LUXURY',
  LUXURY = 'LUXURY',
  EXPRESSWAY = 'EXPRESSWAY',
  AC = 'AC',
  SCHOOL = 'SCHOOL',
  SPECIAL = 'SPECIAL',
  EXPRESS = 'EXPRESS',
}

export enum VehicleStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  RETIRED = 'RETIRED',
}

export enum RouteStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export enum StopStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum FareSourceType {
  NTC_OFFICIAL = 'NTC_OFFICIAL',
  OPERATOR = 'OPERATOR',
  ESTIMATED = 'ESTIMATED',
  UNAVAILABLE = 'UNAVAILABLE',
}

export enum TripStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DELAYED = 'DELAYED',
  CANCELLED = 'CANCELLED',
  BREAKDOWN = 'BREAKDOWN',
  DIVERTED = 'DIVERTED',
}

export enum OccupancyLevel {
  EMPTY = 'EMPTY',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  FULL = 'FULL',
}

export enum AlertType {
  DELAY = 'DELAY',
  CANCELLATION = 'CANCELLATION',
  DIVERSION = 'DIVERSION',
  BREAKDOWN = 'BREAKDOWN',
  ROUTE_CHANGE = 'ROUTE_CHANGE',
  FARE_CHANGE = 'FARE_CHANGE',
  SERVICE_DISRUPTION = 'SERVICE_DISRUPTION',
  GENERAL = 'GENERAL',
}

export enum AlertSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUNDED = 'REFUNDED',
  NO_SHOW = 'NO_SHOW',
}

export enum TicketStatus {
  ISSUED = 'ISSUED',
  VALIDATED = 'VALIDATED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  INVALID = 'INVALID',
}

export enum PaymentMethod {
  CARD = 'CARD',
  MOBILE_WALLET = 'MOBILE_WALLET',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CASH_ON_BOARDING = 'CASH_ON_BOARDING',
  OPERATOR_METHOD = 'OPERATOR_METHOD',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum RefundStatus {
  REQUESTED = 'REQUESTED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum NotificationType {
  BUS_APPROACHING = 'BUS_APPROACHING',
  DEPARTURE_REMINDER = 'DEPARTURE_REMINDER',
  DELAY = 'DELAY',
  CANCELLATION = 'CANCELLATION',
  ROUTE_CHANGE = 'ROUTE_CHANGE',
  FARE_CHANGE = 'FARE_CHANGE',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  REFUND_INITIATED = 'REFUND_INITIATED',
  REFUND_COMPLETED = 'REFUND_COMPLETED',
  SERVICE_DISRUPTION = 'SERVICE_DISRUPTION',
  SYSTEM = 'SYSTEM',
}

export enum ComplaintCategory {
  INCORRECT_FARE = 'INCORRECT_FARE',
  BUS_LATE = 'BUS_LATE',
  UNSAFE_DRIVING = 'UNSAFE_DRIVING',
  CONDUCTOR_BEHAVIOR = 'CONDUCTOR_BEHAVIOR',
  TICKETING_ISSUE = 'TICKETING_ISSUE',
  APP_ERROR = 'APP_ERROR',
  OTHER = 'OTHER',
}

export enum ComplaintStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  REFERRED = 'REFERRED',
  CLOSED = 'CLOSED',
}

export enum Locale {
  EN = 'en',
  SI = 'si',
  TA = 'ta',
}

export const CURRENCY = 'LKR' as const;
export type Currency = typeof CURRENCY;
